### ISSUE TITLE
Allow TSML.Outliernicers.Outliernicer range to be changed.

### ISSUE THREAD

**Issue by rustyconover** [IBM/TSML.jl#165]
Right now the outliers are determined as being outside of 0.25 and 0.75 the IQR, it would be nice if that range is configurable.

Thanks,

Rusty

**Comment by ppalmes** [comment]
thanks for the feedback. which do you think is practical?  absolute range or still a factor of IQR?

**Comment by ppalmes** [comment]
is this ok? let factor=1.5:  then range is (median-factor*iqr, median+factor*iqr)

**Comment by ppalmes** [comment]
as a temporary solution, you can overwrite the transform! function.

```
using TSML
import TSML.transform!

function transform!(st::Outliernicer, features::DataFrame)
             features != DataFrame() || return DataFrame()
             ncol(features) == 2 || error("dataframe must have 2 columns: Date, Val")
             sum(names(features) .== ("Date","Value"))  == 2 || error("wrong column names")
             mfeatures=deepcopy(features)
             rvals = mfeatures.Value
             # compute the outlier range
             # setup to store both missing and numbers
             mvals = Array{Union{Missing,eltype(rvals)},1}(missing,length(rvals))
             mvals .= rvals
             crvals = skipmissing(rvals) # stat of non-missing
             miqr = iqr(crvals)
             m  = quantile(crvals,0.5) ##median
             lower=m-1.5*miqr; upper=m+1.5*miqr
             missindx = findall(x -> !ismissing(x) && (x > upper || x < lower),rvals)
             mvals[missindx] .= missing
             mfeatures.Value = mvals
             # use ValNNer to replace missings
             valnner = DateValNNer(st.args)
             fit!(valnner,mfeatures)
             resdf = transform!(valnner,mfeatures)
             resdf.Value = collect(skipmissing(resdf.Value))
             resdf
end

**Comment by rustyconover** [comment]
Personally I like using IQR but I'm far from an expert.

I really like this package because I've been using it to replace missing values in some time series I've been working with.   It makes it so simple. @ppalmes Thank you for creating it!

The Readme.md mentions:

> TS ML wrapper with more than 100+ libraries from caret, scikitlearn, and julia

Are these examples of using that wrapper?

Rusty

**Comment by ppalmes** [comment]
Thanks for the nice feedback!

The latest master branch now contains the option to pass the scale factor:
```
    Outliernicer(Dict(
       :dateinterval => Dates.Hour(1),
       :nnsize => 1,
       :missdirection => :symmetric,
       :scale => 1.25
    ))
```

I refactor TSML and placed the ML part to AutoMLPipeline (https://github.com/IBM/AutoMLPipeline.jl). The moment the time-series is matrified using Matrifier and Dateifier (https://ibm.github.io/TSML.jl/dev/man/valueproc/), you can use the AutoMLPipeline to do the machine learning using ScikitLearn. Caret is problematic to be added because I want to support Windows/Linus/Mac. I highly recommend you to try AutoMLPipeline.

**Comment by ppalmes** [comment]
it will use the scale factor: median-scale*IQR, median+scale*IQR

after all test passes, I will register a new version with these changes.

**Comment by ppalmes** [comment]
PR #166

**Comment by ppalmes** [comment]
I just registered a new version. you can update your TSML copy once it's accepted in General registry.

**Comment by rustyconover** [comment]
@ppalmes thank you! :)
