### ISSUE TITLE
When using TSML warning about Plots is displayed

### ISSUE THREAD

**Issue by rustyconover** [IBM/TSML.jl#171]
When `using TSML` this message is displayed.

```
┌ Warning: Package TSML does not have Plots in its dependencies:
│ - If you have TSML checked out for development and have
│   added Plots as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with TSML
└ Loading Plots into TSML from project dependency, future warnings for TSML are suppressed.
```

**Comment by ppalmes** [comment]
Please update to the latest version (2.5.7). This warning happens pre-2.5.7 because I removed Plots.jl as a dependency and replaced it with RecipesBase.jl to speed up the loading time. Loading will be relatively faster now in the latest version.

**Comment by ppalmes** [comment]
Because of using RecipesBase.jl, please load Plots.jl if you want to use TSML.Plotters.Plotter functionality.
