### ISSUE TITLE
StaticPlotting.jl crashes with julia >= 1.8.5

### ISSUE THREAD

**Issue by dimsinel** [IBM/TSML.jl#202]
Hello.

I seem to bump on a problem w/ StaticPlotting.jl.ipyng. Specifically, 
fit!(mypipeline, df) 
returns  a BoundsError: attempt to access 0-element Vector{Machine} at index [0]

Tested it both locally  (1.8.5 and 1.9.0 3c2) and on binder with 1.8.5

The full error message from Binder is:
BoundsError: attempt to access 0-element Vector{Machine} at index [0]

Stacktrace:
 [1] getindex(A::Vector{Machine}, i1::Int64)
   @ Base ./array.jl:924
 [2] fit!(pipe::Pipeline, features::DataFrame, labels::Vector{Any})
   @ AMLPipelineBase.Pipelines /srv/julia/pkg/packages/AMLPipelineBase/sH55F/src/pipelines.jl:88
 [3] fit!(pipe::Pipeline, features::DataFrame)
   @ AMLPipelineBase.Pipelines /srv/julia/pkg/packages/AMLPipelineBase/sH55F/src/pipelines.jl:72
 [4] top-level scope
   @ In[4]:8

And from my laptop w/ 1.9.0-rc2+0.x64.linux.gnu : 
BoundsError: attempt to access 0-element Vector{Machine} at index [0]
AutoMLPipeline
Stacktrace:
 [1] getindex(A::Vector{Machine}, i1::Int64)
   @ Base ./essentials.jl:13
 [2] fit!(pipe::Pipeline, features::DataFrame, labels::Vector{Any})
   @ AMLPipelineBase.Pipelines ~/.julia/packages/AMLPipelineBase/sH55F/src/pipelines.jl:88
 [3] fit!(pipe::Pipeline, features::DataFrame)
   @ AMLPipelineBase.Pipelines ~/.julia/packages/AMLPipelineBase/sH55F/src/pipelines.jl:72
 [4] top-level scope
   @ ~/work/julia/TimeSeries/TSML.jl.notebooks/StaticPlotting.jl.ipynb:1

**Comment by ppalmes** [comment]
thanks for raising the issue. the unit-testing does not catch plotting so i may have missed this issue. i'll take a look and get back here. also, the Plots.jl has undergone many changes so it can be due to changes in the API issue.

**Comment by ppalmes** [comment]
i fixed the issue in the latest release which will be in 2.7.4 or you can manually point to the main branch to try it.
```
using Pkg
Pkg.add("https://github.com/IBM/TSML.jl")
```

**Comment by dimsinel** [comment]
Hi.
Am i doing something wrong here? 
I get almost the same error as before -- just changed by one line number, from pipelines.jl 88 to 89:

fit!(mypipeline, df)

BoundsError: attempt to access 0-element Vector{Machine} at index [0]

Stacktrace:
 [1] getindex(A::Vector{Machine}, i1::Int64)
   @ Base ./essentials.jl:13
 [2] fit!(pipe::Pipeline, features::DataFrame, labels::Vector{Any})
   @ AMLPipelineBase.Pipelines ~/.julia/packages/AMLPipelineBase/sH55F/src/pipelines.jl:89
 [3] fit!(pipe::Pipeline, features::DataFrame)
   @ AMLPipelineBase.Pipelines ~/.julia/packages/AMLPipelineBase/sH55F/src/pipelines.jl:73
 [4] top-level scope
   @ ~/work/julia/TimeSeries/TSML.jl.notebooks/StaticPlotting.jl.ipynb:1

______________________________
julia> VERSION
v"1.9.0-rc2"

julia> Pkg.status()
Status `~/work/julia/TimeSeries/Project.toml`
  [e3c3008a] AMLPipelineBase v0.1.12
  [08437348] AutoMLPipeline v0.4.0
  [336ed68f] CSV v0.10.9
  [a93c6f00] DataFrames v1.5.0
  [945b72a4] MarketData v0.13.12
  [ef544631] Pipelines v0.10.0
  [91a5bcdd] Plots v1.38.9
  [198dc43e] TSML v2.7.4 `https://github.com/IBM/TSML.jl#master`
  [bd369af6] Tables v1.10.1
  [9e3dc215] TimeSeries v0.23.1
  [ade2ca70] Dates

**Comment by ppalmes** [comment]
try 
using Plots 
because i'm using Plot recipes to avoid  Plots as a dependency during TSML loading which used to be heavy. Recently, Plots is quick so i may just include Plots as a dependency in the future.

**Comment by ppalmes** [comment]
also, try running the StaticPlotting notebook because I edited it to include the correct dependencies.

**Comment by ppalmes** [comment]
you can slack me by the way in julia slack if you have still issues.

**Comment by ppalmes** [comment]
please close this issue if you think it's fixed.

**Comment by dimsinel** [comment]
Yes, it works fine. 

Case closed.

**Comment by ppalmes** [comment]
glad to help and thanks for the feedback.
